trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
- name: buildConfiguration
  displayName: Build Configuration
  type: string
  default: Release
  values:
  - Release
  - Debug

steps:
- script: dotnet build --configuration ${{ parameters.buildConfiguration }}
  displayName: Build

- script: dotnet test --no-restore --configuration ${{ parameters.buildConfiguration }}
  displayName: Test