<Project>

  <Import
    Condition="'$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))' != ''"
    Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />

    <!-- Tooling -->
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="6.0.3" />

    <!-- Testing -->
    <PackageVersion Include="nunit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>

</Project>
