<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rcm.Persistence.Abstractions\Rcm.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\Rcm.Sensors.Abstractions\Rcm.Sensors.Abstractions.csproj" />
  </ItemGroup>

</Project>
