<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rcm.DataCollection.Api\Rcm.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\Rcm.Sensors.Abstractions\Rcm.Sensors.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

</Project>
