<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <!-- Ensure TSC runs before static assets are processed -->
    <PrepareForBuildDependsOn>CompileTypeScriptWithTSConfig;GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rcm.Aggregates\Rcm.Aggregates.csproj" />
    <ProjectReference Include="..\Rcm.Sensors.Bme280\Rcm.Sensors.Bme280.csproj" />
    <ProjectReference Include="..\Rcm.DataCollection\Rcm.DataCollection.csproj" />
    <ProjectReference Include="..\Rcm.I2c\Rcm.I2c.csproj" />
    <ProjectReference Include="..\Rcm.Sensors.Fakes\Rcm.Sensors.Fakes.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <!--
      The files may not exist at build evaluation time due to npm install not having run yet.
      Absence of actual files causes wildcards expansion in Item->Include to fail so project-level items cannot be used for this.
    -->
    <NpmPackageFiles>
      node_modules\flatpickr\dist\flatpickr.css;
      node_modules\flatpickr\dist\flatpickr.min.css;
      node_modules\flatpickr\dist\esm\**
    </NpmPackageFiles>
  </PropertyGroup>

  <Target Name="EnsureNodeAndPackages" BeforeTargets="BeforeBuild" Condition="!Exists('node_modules')">
    <Exec Command="node --version" ContinueOnError="true" StandardOutputImportance="low">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using npm..." />
    <Exec Command="npm install --quiet --no-progress" />
  </Target>

  <Target Name="CopyNpmPackageFiles" AfterTargets="EnsureNodeAndPackages">
    <ItemGroup>
      <_NpmPackageFile Include="$(NpmPackageFiles)" />
    </ItemGroup>

    <Copy SourceFiles="@(_NpmPackageFile)" DestinationFiles="@(_NpmPackageFile -> 'wwwroot\lib$([System.String]::new(%(Identity)).TrimStart('node_modules'))')" SkipUnchangedFiles="true" />

  </Target>

</Project>
